CREATE DATABASE `studydb`;
USE `studydb`;
CREATE TABLE IF NOT EXISTS `USERS`(
    `ID` int(5) NOT NULL AUTO_INCREMENT,
    `FIRSTNAME` VARCHAR(30) DEFAULT NULL,
    `LASTNAME` VARCHAR(30) DEFAULT NULL,
    `BIRTHDAY` DATE DEFAULT NULL,
    `FACEBOOK` VARCHAR(100) DEFAULT NULL,
    `EMAIL` VARCHAR(100) DEFAULT NULL,
    `PHONE` VARCHAR(12) DEFAULT NULL,
    `OCCUPATION` VARCHAR(100) DEFAULT NULL,
    `COMPANY` VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY(`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `CATEGORIES`(
    `ID` int(5) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(20) DEFAULT NULL,
    `DETAILS` VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `LEARNPATHS`(
    `ID` int(5) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(20) DEFAULT NULL,
    `DETAILS` VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `RESOURCEGROUPS`(
    `ID` int(5) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(20) DEFAULT NULL,
    `DETAILS` VARCHAR(100) DEFAULT NULL,
    `USERID` int(5) DEFAULT NULL,
    `CATEGORYID` int(5) DEFAULT NULL,
    `LEARNPATHID` int(5) DEFAULT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`USERID`) REFERENCES `USERS`(`ID`),
    FOREIGN KEY (`CATEGORYID`) REFERENCES `CATEGORYS`(`ID`),
    FOREIGN KEY (`LEARNPATHID`) REFERENCES `LEARNPATHS`(`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `RESOURCES` (
    `ID` int(5) NOT NULL AUTO_INCREMENT,
    `NAME` varchar(200) DEFAULT NULL,
    `PATH` varchar(100) DEFAULT NULL,
    `DETAILS` varchar(200) DEFAULT NULL,
    `USERID` int(5) DEFAULT NULL,
    `GROUPID` int(5) DEFAULT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`USERID`) REFERENCES `USERS`(`ID`),
    FOREIGN KEY (`GROUPID`) REFERENCES `RESOURCEGROUPS`(`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;